//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemmanagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Users()
        {
            this.TB_UserHistory = new HashSet<TB_UserHistory>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> RoleId_Fk { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string LastLogin { get; set; }
    
        public virtual TB_Roles TB_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_UserHistory> TB_UserHistory { get; set; }
    }
}
